### ISSUE TITLE
FLOW-MOD-TABLE-FULL 

### ISSUE THREAD

**Issue by DFritzsche** [bisdn/xdpd#76] opened 2015-06-18 12:42 UTC
Can we please have more detailed cofmsg_error messages than the standard FLOW-MOD-TABLE-FULL. (and the table I use is not full)

**Comment by msune** [comment] 2015-06-18 15:34
OpenFlow does not capture all the possible issues that can occur in a SW datapath (e.g. out-of-memory conditions).

It should be first checked which is the root cause of the failure during insertion (out of memory? validation? any other issue?), and if there is a more appropriate error code use it. Please provide more info.

**Comment by DFritzsche** [comment] 2015-06-19 13:23
The msg

`---Error msg received ---  DPT:<cdpid 256 >
<cofmsg version: 4 type: 1 length: 76 xid: 0xfdaa22ef >
  <cofmsg_error >
    <error-id: 0x50001 FLOW-MOD-TABLE-FULL >
      <cmemory: data:0x7f71ec001180 datalen:64 >
        0000: 04 0e 00 58 fd aa 22 ef   03 00 00 00 00 00 00 00   00 00 00 00 00 00 00 00   3c 00 00 00 00 00 00 02   
        0001: ff ff ff ff ff ff ff fd   ff ff ff ff 00 00 00 00   00 01 00 14 80 00 06 06   ff ff ff ff ff ff 80 00`

is caused by

```
[rofl-pipeline] [flowmod-add(0x1d5b5110)] Starting operation at switch dp0(0x1d50cf70), table 60, with flags:  
[rofl-pipeline] Entry (0x1d5b5110), prior. 2, cookie 0x300000000000000, pkts.matched 0. Matches:{[ETH_DST:0xffffffffffff|0xffffffffffff],  [ETH_TYPE:0x806], }
[rofl-pipeline]         Inst->>  WRITE, 
[rofl-pipeline]             WR.ACTIONs:<GROUP:65537>,
[rofl-pipeline] [flowmod-add(0x1d5b5110)] FAILED validation. Ignoring...
[xdpd][of13][flow-mod-add] error inserting flow-mod on dpt:dp0
eFlowModTableFull <cofmsg_flow_mod >
  <cofmsg version: 4 type: 14 length: 88 xid: 0xfdaa22ef >
    <cofflowmod ofp-version:4 >
      <command: ADD >
      <cookie: 0x300000000000000 >
      <cookie-mask: 0x0 >
      <table-id: 60 >
      <idle-timeout: 0 >
      <hard-timeout: 0 >
      <priority: 0x2 >
      <buffer-id: 0xffffffff >
      <out-port: 0xfffffffd >
      <out-group: 0xffffffff >
  <flags: 0x0 >
  <cofmatch ofp-version:4 >
    <type: 1 >
  <coxmatches #matches:2 >
    <coxmatch oxm-id: 0x80000606 >
      <cmemory: data:0x1d51ea30 datalen:10 >
        0000: 80 00 06 06 ff ff ff ff   ff ff 
      <eth-dst: ff:ff:ff:ff:ff:ff/ff:ff:ff:ff:ff:ff >
    <coxmatch oxm-id: 0x80000a02 >
      <cmemory: data:0x1d51ea30 datalen:6 >
        0000: 80 00 0a 02 08 06 
      <eth-type: 0x806 >
<cofintructions ofp-version:4 >
  <cofinstruction_write_actions >
    <cofinstruction_actions >
      <cofinstruction type: 0x3 length: 16 >
        <cofactions ofp-version:4 #actions:1 >
          <cofaction_group group-id:0x10001 >
            <cofaction ofp-version:4 type:0x16 length:8  >

[rofl-pipeline] Packet[0x11fddd0] Processing PKT_OUT, action group: <OUTPUT port: 1>,
[rofl-pipeline] Packet[0x11fddd0] {PORT_IN:4294967293, ETH_SRC:0xfa163edc4bc9, ETH_DST:0xffffffffffff, ETH_TYPE:0x88cc, }
[rofl-pipeline] Packet[0x11fddd0] outputting to port num. 1
```

**Comment by msune** [comment] 2015-06-19 13:54
Failure occurs due to the group ID not existing, likely. Then the error message is incorrect and should be fixed with `OFPET_BAD_ACTION` or `OFPET_BAD_INSTRUCTION`

**Comment by DFritzsche** [comment] 2015-06-22 08:14
Can confirm that the group ID does not exist.

The group is not created because of `eGroupModChainingUnsupported`. Then, when I refer t that group it throws `FLOW-MOD-TABLE-FULL`.

**Comment by msune** [comment] 2015-07-28 13:10
Fixed merged

**Closed as completed by msune** 2015-07-28 13:10 UTC
Labels: bug
