### ISSUE TITLE
gnu-linux: devel-06 doesn't compile

### ISSUE THREAD

**Issue by zslot** [bisdn/xdpd#47] opened 2015-02-19 18:01 UTC
current head doesn't compile

```
make[8]: Betrete Verzeichnis '/home/zsolt/workspace/eclipse/xdpd/build/src/xdpd/drivers/gnu_linux/src/io/ports/mmap'
  CXX      mmap_rx.lo
  CXX      mmap_tx.lo
  CXX      ioport_mmap.lo
In file included from /usr/include/x86_64-linux-gnu/bits/byteswap.h:35:0,
                 from /usr/include/endian.h:60,
                 from /usr/include/ctype.h:39,
                 from /usr/include/c++/4.8/cctype:42,
                 from /usr/include/c++/4.8/bits/localefwd.h:42,
                 from /usr/include/c++/4.8/string:43,
                 from ../../../../../../../../../src/xdpd/drivers/gnu_linux/src/io/ports/mmap/ioport_mmap.h:10,
                 from ../../../../../../../../../src/xdpd/drivers/gnu_linux/src/io/ports/mmap/ioport_mmap.cc:1:
../../../../../../../../../src/xdpd/drivers/gnu_linux/src/io/ports/mmap/ioport_mmap.cc: In member function 'void xdpd::gnu_linux::ioport_mmap::fill_vlan_pkt(tpacket2_hdr*, xdpd::gnu_linux::datapacketx86*)':
../../../../../../../../../src/xdpd/drivers/gnu_linux/src/io/ports/mmap/ioport_mmap.cc:170:82: error: 'struct tpacket2_hdr' has no member named 'tp_vlan_tpid'
  ((struct fetherframe::eth_hdr_t*)pkt_x86->get_buffer())->dl_type = htobe16(hdr->tp_vlan_tpid);
                                                                                  ^
make[8]: *** [ioport_mmap.lo] Fehler 1
```
Linux lofraxel 3.13.0-45-generic #74-Ubuntu SMP Tue Jan 13 19:36:28 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by msune** [comment] 2015-02-19 20:04
Thanks

Confirmed also with Linux kernel 3.2.0. The commit that breaks compilation for older kernels is:

https://github.com/bisdn/xdpd/commit/3c10d72ce1b1cd27492c6becbf960075e54606a1

I think the solution is to also ifdef the code based on `TP_STATUS_VLAN_VALID`, as we do already here:

https://github.com/bisdn/xdpd/blob/3c10d72ce1b1cd27492c6becbf960075e54606a1/src/xdpd/drivers/gnu_linux/src/io/ports/mmap/ioport_mmap.cc#L249-253

 @akoepsel are you handling it, or shall I take over?

**Comment by msune** [comment] 2015-02-19 20:07
Possibly related to the new `tp_vlan_tpid` field #42. Could be that now the auxiliary struct needs to be filled in as in RX, as was always meant to be.

**Comment by akoepsel** [comment] 2015-02-20 03:35
I added a vlan.m4 macro to the GNU-Linux driver for testing for kernels supporting the tp_vlan_tpid field (since 3.14.0). For older kernels or when the kernel version cannot be detected, the old behaviour is used with setting the ethernet type to vlan C-TAG (0x8100) in a static manner. However, in this case, we dump a warning to the user, as this might lead to unexpected behaviour.

**Comment by msune** [comment] 2015-02-20 07:28
Yes, this is a far better solution than ifdefing `TP_STATUS_VLAN_VALID`, since we can warn the user at configure time.

There is an issue; I think if you only have the headers, you don't have the Makefiles:
```
checking for vlan S-TAG/I-TAG header support in kernel... sed: can't read /lib/modules/3.2.0-4-amd64/build/Makefile: No such file or directory
sed: can't read /lib/modules/3.2.0-4-amd64/build/Makefile: No such file or directory
sed: can't read /lib/modules/3.2.0-4-amd64/build/Makefile: No such file or directory
configure: WARNING: unable to detect kernel version, continuing anyway, vlan S-TAG/I-TAG headers may not work
```

Maybe it is just easier, instead of having to deduce it from `uname` and lib/modules kernel the vesion, to have an `AC_COMPILE_IFELSE`, include the header create a struct `tpacket2_hdr` in stack, and attempt to access `tp_vlan_tpid`. If it compiles, then kernel is good, otherwise it is old, then print the nice message. I would also put a sleep after that, just to make it more noticeable to the user. Otherwise all goes fast, you never notice.

Thanks

**Comment by msune** [comment] 2015-02-23 06:55
It seems that, at least in my machine with kernel 3.16, the `tp_vlan_tpid` is not correctly detected either:

```
checking for vlan S-TAG/I-TAG header support in kernel... configure: WARNING: kernel does not support vlan S-TAG/I-TAG headers, consider upgrading to at least kernel version 3.14.x
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating src/hal-imp/Makefile
config.status: creating src/hal-imp/openflow/openflow1x/Makefile
config.status: creating src/io/Makefile
config.status: creating src/io/packet_classifiers/Makefile
config.status: creating src/io/packet_classifiers/c_types_pktclassifier/Makefile
config.status: creating src/io/ports/Makefile
config.status: creating src/io/ports/mmap/Makefile
config.status: creating src/io/ports/mockup/Makefile
config.status: creating src/io/ports/vlink/Makefile
config.status: creating src/io/scheduler/Makefile
config.status: creating src/pipeline-imp/Makefile
config.status: creating src/processing/Makefile
config.status: creating src/util/Makefile
config.status: creating test/Makefile
config.status: creating test/regression/Makefile
config.status: creating test/regression/io/Makefile
config.status: creating test/unit/Makefile
config.status: creating test/unit/util/Makefile
config.status: creating test/unit/io/Makefile
config.status: creating test/unit/io/packet_classifiers/Makefile
config.status: creating test/unit/io/packet_classifiers/c_pktclassifier/Makefile
config.status: creating test/unit/io/packet_classifiers/c_pktclassifier/headers/Makefile
config.status: executing depfiles commands
config.status: executing libtool commands
marc@dev:~/git/bisdn/xdpd/build$ uname -a
Linux dev 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt2-1 (2014-12-08) x86_64 GNU/Linux
marc@dev:~/git/bisdn/xdpd/build$ grep tp_vlan_tpid /usr/include/ -R
/usr/include/linux/if_packet.h:	__u16		tp_vlan_tpid;
/usr/include/linux/if_packet.h:#define TP_STATUS_VLAN_TPID_VALID	(1 << 6) /* auxdata has valid tp_vlan_tpid */
/usr/include/linux/if_packet.h:	__u16		tp_vlan_tpid;
/usr/include/linux/if_packet.h:	__u16	tp_vlan_tpid;
```

I take it over.

**Comment by msune** [comment] 2015-02-23 08:00
Tried with 3.2.0 and 3.16.0. Seems it works. Closing issue

**Closed by msune** 2015-02-23 08:00 UTC
Labels: bug, Fix applied, gnu-linux
